package org.example;

public class Main {
    public static void main(String[] args) {
        // CREATE A METHOD TO CHECK IF GIVEN VALUSE OF 3 SIDES OF TRIANGLES WILL RESULT A TRIANGLE WITH AN RIGHT ANGLE
        // BASED ON PYTHAGOREAN THEOREM IF THE SQR OF HYPOTENUSE IS EQUAL TO THE SUM OF THE OTHER TWO SIDES SQR SO THE TRIANGLE IS A RIGHT ANGLE TRIANGLE
        // PYTHAGOREAN EQUATION: A^ = B^2 + C^2
    }
}